version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pyrex
      POSTGRES_PASSWORD: pyrex_pass
      POSTGRES_DB: pyrex_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db-data:
